{% set name = "rocfft" %}
{% set version = "1.0.25" %}
{% set rocm_version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/rocFFT/archive/refs/tags/rocm-{{ rocm_version }}.tar.gz
  sha256: d3e1f7a4dc661f1e5ffce02e2e01ae6c3c339bac8e93deaf175e4c03ddfea459
  patches:
    - 0001-Make-rocm-cmake-mandatory.patch
    - 0001-Add-find_package-hip.patch
    - 0001-Fix-mman-include-for-MADV_HUGEPAGE.patch
    - 0001-Disable-ahead-of-time-kernel-compilation.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - compiler-rt
    - clangdev
    - hip-devel
    - hipcc
    - lld
    - rocm-cmake
    - rocm-device-libs
    - sqlite

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://rocm.docs.amd.com/projects/rocFFT
  summary: rocFFT library
  description: |
    rocFFT is a software library for computing fast Fourier transforms (FFTs)
    written in the HIP programming language. It's part of AMD's software ecosystem
    based on ROCm. The rocFFT library can be used with AMD and NVIDIA GPUs.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://rocm.docs.amd.com/projects/rocFFT
  dev_url: https://github.com/ROCm/rocFFT

extra:
  recipe-maintainers:
    - zklaus
